// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfyTe2HnBODnzJJVbvPwi2t4PMc75eOGM',
    appId: '1:904230394024:web:cda31d4376fb90174bca9d',
    messagingSenderId: '904230394024',
    projectId: 'qori-4b6f3',
    authDomain: 'qori-4b6f3.firebaseapp.com',
    storageBucket: 'qori-4b6f3.firebasestorage.app',
    measurementId: 'G-L5PMYK6QDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbJDEspRpMPCeGGNym4gmDdYTLG-cMwVQ',
    appId: '1:904230394024:android:943e41c0f1afea384bca9d',
    messagingSenderId: '904230394024',
    projectId: 'qori-4b6f3',
    storageBucket: 'qori-4b6f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8jDcaPHsQR9rOWKwbHTJQNq_ePzvdxaI',
    appId: '1:904230394024:ios:c0c86f66590c925e4bca9d',
    messagingSenderId: '904230394024',
    projectId: 'qori-4b6f3',
    storageBucket: 'qori-4b6f3.firebasestorage.app',
    iosBundleId: 'com.example.qori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8jDcaPHsQR9rOWKwbHTJQNq_ePzvdxaI',
    appId: '1:904230394024:ios:c0c86f66590c925e4bca9d',
    messagingSenderId: '904230394024',
    projectId: 'qori-4b6f3',
    storageBucket: 'qori-4b6f3.firebasestorage.app',
    iosBundleId: 'com.example.qori',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfyTe2HnBODnzJJVbvPwi2t4PMc75eOGM',
    appId: '1:904230394024:web:f51dc0c7f848a2894bca9d',
    messagingSenderId: '904230394024',
    projectId: 'qori-4b6f3',
    authDomain: 'qori-4b6f3.firebaseapp.com',
    storageBucket: 'qori-4b6f3.firebasestorage.app',
    measurementId: 'G-W9RJZDPRLJ',
  );

}